import { readFile } from "node:fs/promises";
import { z } from "zod";
import { createFinding } from "./risk.js";
import { redactSecrets } from "./redaction.js";
import { JsonObjectSchema, SeveritySchema, type AgentRun, type JsonValue, type McpToolDescriptor, type RiskFinding, type Severity } from "./schemas.js";

export type FirewallAction = "allow" | "deny" | "escalate";

const FirewallMatchSchema = z
  .object({
    serverName: z.string().min(1).optional(),
    serverNamePattern: z.string().min(1).optional(),
    toolName: z.string().min(1).optional(),
    toolNamePattern: z.string().min(1).optional()
  })
  .strict();

const FirewallConditionsSchema = z
  .object({
    forbiddenSubstrings: z.array(z.string().min(1)).optional(),
    allowedPaths: z.array(z.string().min(1)).optional(),
    maxStringLength: z.number().int().positive().optional()
  })
  .strict();

const FirewallRuleSchema = z
  .object({
    id: z.string().min(1),
    decision: z.enum(["allow", "deny", "escalate"]),
    severity: SeveritySchema.optional(),
    reason: z.string().min(1),
    match: FirewallMatchSchema,
    conditions: FirewallConditionsSchema.optional()
  })
  .strict();

export const FirewallConfigSchema = z
  .object({
    schemaVersion: z.literal(1),
    generatedAt: z.string().min(1),
    description: z.string().optional(),
    defaultDecision: z.enum(["allow", "deny", "escalate"]),
    rules: z.array(FirewallRuleSchema)
  })
  .strict();

export type FirewallRule = z.infer<typeof FirewallRuleSchema>;
export type FirewallConfig = z.infer<typeof FirewallConfigSchema>;

export interface CreateFirewallConfigOptions {
  generatedAt?: string;
  description?: string;
}

export interface FirewallToolCallInput {
  timestamp: string;
  serverName?: string;
  toolName: string;
  arguments: Record<string, JsonValue>;
}

export interface FirewallDecision {
  action: FirewallAction;
  ruleId?: string;
  severity?: Severity;
  reason: string;
  finding?: RiskFinding;
}

export interface FirewallEvent {
  id: string;
  timestamp: string;
  action: FirewallAction;
  ruleId?: string;
  severity?: Severity;
  reason: string;
  runId?: string;
  toolCallId?: string;
  serverName?: string;
  toolName: string;
  arguments: Record<string, JsonValue>;
  finding?: RiskFinding;
}

export interface FirewallReport {
  schemaVersion: 1;
  generatedAt: string;
  summary: {
    evaluated: number;
    allowed: number;
    denied: number;
    escalated: number;
    findings: number;
    critical: number;
    high: number;
    medium: number;
    low: number;
    info: number;
  };
  events: FirewallEvent[];
  findings: RiskFinding[];
}

export interface SimulateFirewallOptions {
  generatedAt?: string;
}

const COMMAND_TOOL_PATTERN = /(shell|exec|execute|run[_-]?command|terminal|powershell|bash|cmd|pwsh|python|node|script|subprocess)/i;

export async function readFirewallConfigFile(path: string): Promise<FirewallConfig> {
  const raw = JSON.parse(await readFile(path, "utf8")) as unknown;
  return FirewallConfigSchema.parse(raw);
}

export function createFirewallConfigFromTools(
  tools: readonly McpToolDescriptor[],
  options: CreateFirewallConfigOptions = {}
): FirewallConfig {
  return {
    schemaVersion: 1,
    generatedAt: options.generatedAt ?? new Date().toISOString(),
    description: options.description ?? "Least-privilege MCP capability firewall policy generated by AgentOps Watchtower.",
    defaultDecision: "deny",
    rules: tools.map((tool) => createRuleForTool(tool))
  };
}

export function evaluateFirewallToolCall(config: FirewallConfig, input: FirewallToolCallInput): FirewallDecision {
  const parsedConfig = FirewallConfigSchema.parse(config);
  const sanitizedInput = {
    ...input,
    arguments: redactSecrets(JsonObjectSchema.parse(input.arguments))
  };

  for (const rule of parsedConfig.rules) {
    if (!matchesRule(rule, sanitizedInput)) {
      continue;
    }
    return createDecision(rule.decision, rule.reason, sanitizedInput, {
      ruleId: rule.id,
      ...(rule.severity === undefined ? {} : { severity: rule.severity })
    });
  }

  return createDecision(parsedConfig.defaultDecision, `No firewall rule matched ${input.toolName}.`, sanitizedInput);
}

export function simulateFirewall(
  config: FirewallConfig,
  runs: readonly AgentRun[],
  options: SimulateFirewallOptions = {}
): FirewallReport {
  const events: FirewallEvent[] = [];
  const findings: RiskFinding[] = [];
  for (const run of runs) {
    const sortedToolCalls = [...run.toolCalls].sort((left, right) => {
      const timestampCompare = left.timestamp.localeCompare(right.timestamp);
      return timestampCompare === 0 ? left.id.localeCompare(right.id) : timestampCompare;
    });
    for (const toolCall of sortedToolCalls) {
      const decision = evaluateFirewallToolCall(config, {
        timestamp: toolCall.timestamp,
        ...(toolCall.serverName === undefined ? {} : { serverName: toolCall.serverName }),
        toolName: toolCall.toolName,
        arguments: toolCall.arguments
      });
      if (decision.finding !== undefined) {
        findings.push(decision.finding);
      }
      events.push({
        id: `firewall-event-${events.length + 1}`,
        timestamp: toolCall.timestamp,
        action: decision.action,
        reason: decision.reason,
        toolName: toolCall.toolName,
        arguments: redactSecrets(toolCall.arguments),
        runId: run.id,
        toolCallId: toolCall.id,
        ...(toolCall.serverName === undefined ? {} : { serverName: toolCall.serverName }),
        ...(decision.ruleId === undefined ? {} : { ruleId: decision.ruleId }),
        ...(decision.severity === undefined ? {} : { severity: decision.severity }),
        ...(decision.finding === undefined ? {} : { finding: decision.finding })
      });
    }
  }

  const counts = countSeverities(findings);
  return {
    schemaVersion: 1,
    generatedAt: options.generatedAt ?? new Date().toISOString(),
    summary: {
      evaluated: events.length,
      allowed: events.filter((event) => event.action === "allow").length,
      denied: events.filter((event) => event.action === "deny").length,
      escalated: events.filter((event) => event.action === "escalate").length,
      findings: findings.length,
      critical: counts.critical,
      high: counts.high,
      medium: counts.medium,
      low: counts.low,
      info: counts.info
    },
    events,
    findings
  };
}

function createRuleForTool(tool: McpToolDescriptor): FirewallRule {
  const decision = classifyToolDecision(tool);
  const severity: Severity | undefined = decision === "allow" ? undefined : decision === "deny" ? "high" : "medium";
  return {
    id: `tool-${sanitizeRuleId(tool.name)}-${decision}`,
    decision,
    ...(severity === undefined ? {} : { severity }),
    reason: createRuleReason(tool, decision),
    match: { toolName: tool.name }
  };
}

function classifyToolDecision(tool: McpToolDescriptor): FirewallAction {
  if (tool.annotations?.destructiveHint === true || COMMAND_TOOL_PATTERN.test(`${tool.name} ${tool.description ?? ""}`)) {
    return "deny";
  }
  if (tool.annotations?.openWorldHint === true) {
    return "escalate";
  }
  if (tool.annotations?.readOnlyHint === true) {
    return "allow";
  }
  return "escalate";
}

function createRuleReason(tool: McpToolDescriptor, decision: FirewallAction): string {
  if (decision === "allow") {
    return `${tool.name} is declared read-only and local-only.`;
  }
  if (decision === "deny") {
    return `${tool.name} can execute commands or destructive actions.`;
  }
  return `${tool.name} can affect external systems or needs human review.`;
}

function matchesRule(rule: FirewallRule, input: FirewallToolCallInput): boolean {
  if (!matchesText(rule.match.toolName, rule.match.toolNamePattern, input.toolName)) {
    return false;
  }
  if (!matchesText(rule.match.serverName, rule.match.serverNamePattern, input.serverName ?? "")) {
    return false;
  }
  return matchesConditions(rule, input);
}

function matchesText(exact: string | undefined, pattern: string | undefined, value: string): boolean {
  if (exact !== undefined && value !== exact) {
    return false;
  }
  if (pattern !== undefined && !new RegExp(pattern, "u").test(value)) {
    return false;
  }
  return true;
}

function matchesConditions(rule: FirewallRule, input: FirewallToolCallInput): boolean {
  const conditions = rule.conditions;
  if (conditions === undefined) {
    return true;
  }
  const violations: boolean[] = [];
  if (conditions.forbiddenSubstrings !== undefined) {
    const text = JSON.stringify(input.arguments).toLowerCase();
    violations.push(conditions.forbiddenSubstrings.some((substring) => text.includes(substring.toLowerCase())));
  }
  if (conditions.maxStringLength !== undefined) {
    const maxStringLength = conditions.maxStringLength;
    violations.push(collectStrings(input.arguments).some((value) => value.length > maxStringLength));
  }
  if (conditions.allowedPaths !== undefined) {
    const pathValues = collectPathLikeStrings(input.arguments);
    violations.push(pathValues.some((path) => !conditions.allowedPaths?.some((allowedPath) => path.startsWith(allowedPath))));
  }
  return violations.some(Boolean);
}

function createDecision(
  action: FirewallAction,
  reason: string,
  input: FirewallToolCallInput,
  options: { ruleId?: string; severity?: Severity } = {}
): FirewallDecision {
  if (action === "allow") {
    return {
      action,
      ...(options.ruleId === undefined ? {} : { ruleId: options.ruleId }),
      reason
    };
  }

  const severity = options.severity ?? (action === "deny" ? "high" : "medium");
  const category = action === "deny" ? "firewall.tool_call_denied" : "firewall.tool_call_requires_approval";
  const title =
    action === "deny" ? `${input.toolName} was denied by the Capability Firewall` : `${input.toolName} requires human approval`;
  const finding = createFinding({
    idSeed: `${input.timestamp}-${input.serverName ?? "local"}-${input.toolName}-${action}-${options.ruleId ?? "default"}`,
    severity,
    category,
    title,
    description: reason,
    recommendation:
      action === "deny"
        ? "Narrow the MCP server capability, change the firewall policy only after review, or use a safer tool."
        : "Require a reviewed approval receipt before forwarding this tool call.",
    target: input.toolName,
    evidence: [JSON.stringify(input.arguments).slice(0, 240)]
  });
  return {
    action,
    ...(options.ruleId === undefined ? {} : { ruleId: options.ruleId }),
    severity,
    reason,
    finding
  };
}

function sanitizeRuleId(value: string): string {
  return value.replaceAll(/[^a-zA-Z0-9_-]+/gu, "_").replaceAll(/^_+|_+$/gu, "");
}

function collectStrings(value: JsonValue): string[] {
  if (typeof value === "string") {
    return [value];
  }
  if (Array.isArray(value)) {
    return value.flatMap((item) => collectStrings(item));
  }
  if (value !== null && typeof value === "object") {
    return Object.values(value).flatMap((child) => collectStrings(child));
  }
  return [];
}

function collectPathLikeStrings(value: JsonValue, key = ""): string[] {
  if (typeof value === "string") {
    return /path|file|dir|directory|workspace|root/iu.test(key) ? [value] : [];
  }
  if (Array.isArray(value)) {
    return value.flatMap((item) => collectPathLikeStrings(item, key));
  }
  if (value !== null && typeof value === "object") {
    return Object.entries(value).flatMap(([childKey, child]) => collectPathLikeStrings(child, childKey));
  }
  return [];
}

function countSeverities(findings: readonly RiskFinding[]): Record<Severity, number> {
  const counts: Record<Severity, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    info: 0
  };
  for (const finding of findings) {
    counts[finding.severity] += 1;
  }
  return counts;
}
